AWSTemplateFormatVersion: 2010-09-09
Description: 'AWS::Instance - sct - security items'
Parameters:
  Portfolio:
    Description: coreservice-dms Portfolio name
    Type: String
  App:
    Description: coreservice-dms App name
    Type: String
  VPC:
    Description: coreservice-dms vpc name
    Type: String
    Default: EnterpriseVpc3
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
        Version: "2012-10-17"
      Path: "/"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - Ref: Role

  SctSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Sub '${Portfolio}-${App}-sg'
      GroupDescription: Allow traffic through to the instances.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 101.1119.1126.148/28
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 101.1119.1216.614/27
      Tags:
        - Key: Portfolio
          Value: !Ref Portfolio
        - Key: App
          Value: !Ref App
      VpcId: 
        Fn::ImportValue: 
            !Sub 'core-network:${VPC}:VpcId'
      
Outputs:
  SecurityGroupId:
    Value: !Ref SctSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}:SecurityGroupId'

  InstanceProfileName:
    Value:
      Ref: InstanceProfile
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:InstanceProfileName"
